### ISSUE TITLE
Elementet abstract skal tilføjes

### ISSUE THREAD

**Issue by thsh77** [dsldk/middelaldertekster#1]
For at teksterne kan optræde fyldestgørende i søgeresultater skal de forsynes med et kort resumé, der redegør for indholdet:

Efter creation-elementet

``` code
<creation>
  <date when="1480">1480-1485</date>
</creation>
```
skal der indsættes et abstract-element således:

``` code
<creation>
  <date when="1480">1480-1485</date>
</creation>
<abstract>
  <ab>Her skrives et resumé af teksten, som er nyttigt i søgeresultatvisninger.</ab>
  </abstract>
```

**Comment by mmsdsl** [comment]
`<p>` ved `<div type ="prose">`: Skal de blive stående? (Det går jeg ud fra, men better safe than sorry!)
