### ISSUE TITLE
jespersen_1573.xml: Strofer inddeles i line groups

### ISSUE THREAD

**Issue by mmsdsl** [dsldk/middelaldertekster#11]

**Comment by mmsdsl** [comment]
Ved direkte udskiftning af p-elementet til lg opstår der fejl. Spørg TH.

**Comment by thsh77** [comment]
Ja, det skyldes, at lg-elementet ikke kan indeholde andet end et eller flere l-elementer. Så du kan 'fore' dine lg-elementer på denne måde:

```code
<lg>
  <l> bla bla bla ... bla bla</l>
</lg>
```

**Comment by mmsdsl** [comment]
Løsning:
`<p>(.*?)</p>` -> `<lg><l>\1<l></lg>`
Dernæst:
`(</l><l>.*?/.*?<lb />(?!</l>))` -> `\1</l>\n<l>` 

Jeg tør dog ikke løse denne opgave før jeg er sikker på de lidt mærkelige inddelinger i jespersen_1573 af salmer og prædiken, se issue #41.
