### ISSUE TITLE
jespersen_1573: Brug af bindestreg i <hi>-tekstdele?

### ISSUE THREAD

**Issue by mmsdsl** [dsldk/middelaldertekster#27]
Fx E6

``` code
<div type="prose"><p><hi rend="Walbaum3"><c function="initials" rend="6">K</c>Jere Venner oc Brødre i Christo Je=</hi>
<lb/>su / Det findis i sandhed klart oc aldelis obenbare /
```

**Comment by thsh77** [comment]
Du kan lave den så den kommer til at se sådan her ud:
```code
Christo Je</hi><lb rend="="/>su / Det findis i sandhed klart oc aldelis
```
Dvs. du skal fjerne alle blanktegn/newlines mellem `</hi>` og `<lb rend="="/>`. Jeg håber på, at vi får lov til at fjerne hi-elementet helt senere.

**Comment by thsh77** [comment]
Kan ikke finde flere eksempler på dette problem. Lukker derfor sagen.
