### ISSUE TITLE
jespersen_1573: Fjern <figure type="notatedMusic">

### ISSUE THREAD

**Issue by thsh77** [dsldk/middelaldertekster#30]
Under `//div[@type="musicalNotation"]` skal alle elementer af typen `<figure type="notatedMusic">` fjernes.

**Comment by mmsdsl** [comment]
Bemærkninger: 60 matches fjernet under `//div[@type="musicalNotation"],` stadig ca. 2000 `<figure type="notatedMusic"/>` der skal tages stilling til.

**Comment by thsh77** [comment]
Ja, du roligt udkommentere dem -- foreløbig i hvert fald. Jeg vil tro, at vi fjerner dem, da vi nøjes med én reference til den nodestump, musikfolkene laver. Da vi desuden altid har @type="musicalNotation" klistret på div-tagget, kan vi godt droppe dem.

**Comment by mmsdsl** [comment]
`<figure type="notatedMusic"/>` er blevet konverteret til `<!-- figure type="notatedMusic" -->`. Lukkes for nu.
