### ISSUE TITLE
jespersen_1573.xml: Hvordan skal {??} behandles?

### ISSUE THREAD

**Issue by mmsdsl** [dsldk/middelaldertekster#34]

**Comment by thsh77** [comment]
Forekomst af '{??}' synes at være Trier-folkenes måde at betegne en usikker læsning. Bare lad dem stå, så kan Marita eller Simon fange dem, når de laver korrektur og tekstkritisk gennemgang af teksterne.

**Comment by mmsdsl** [comment]
Meget fint, så lukker jeg denne issue for nu.
