### ISSUE TITLE
jespersen_1573.xml: Mystisk formatering E13 (skal det stå sådan?)

### ISSUE THREAD

**Issue by mmsdsl** [dsldk/middelaldertekster#35]
Page break under div type psalm. Kan det passe? Må jeg flytte den, eller er den tegn på et andet (og måske større) problem?

**Comment by thsh77** [comment]
Den skal flyttes hen foran det første stykke tekst på pågældende side.

**Comment by thsh77** [comment]
Dette er effektueret. Sagen lukkes.
