### ISSUE TITLE
Jespersen_1573.xml: Overordnede div'er for kirkeårets dage

### ISSUE THREAD

**Issue by mmsdsl** [dsldk/middelaldertekster#67]
Inddelingen i overordnede div'er giver mig lidt problemer med visningen, da en "indpakning" i en ny div skjuler overskriften. Hvordan løses dette problem? 

![drilske div er](https://user-images.githubusercontent.com/37372081/42157752-e6035204-7dee-11e8-9bb4-c2a323e2e881.png)

Skal head-elementet rykkes som på nederste billede? Giver det problemer ift. xml id i underdiv'en?

![drilske div er 2](https://user-images.githubusercontent.com/37372081/42157970-654f7df8-7def-11e8-8514-685886ff82dd.png)

**Comment by thsh77** [comment]
Den nederste fremgangsmåde er den korrekte, og heri er det for jespersen bestemt, at den naturlige inddeling er efter kirkeårets messer og herunder efter messens bestanddele (fx Introitus, Sanctus), jf. nedenfor.

```code
<body>
            <div xml:id="foerste-soendag-i-advent">
                <head type="add">Første søndag i advent</head>
                <head>
                    <pb ana="1" n="E13"/>
                    <orig>Den<ex>n</ex> Første Søndag <lb/> i Aduent.</orig>
                    <reg>Første søndag i advent</reg>
                </head>
                <div xml:id="foerste-soendag-i-advent-introitus-da" type="chapter">
                    <figure type="image"/>
                    <head type="add">Introitus (dansk)</head>
                    <head>
                        <orig>Introitus dansk.</orig>
                        <reg>Introitus (dansk)</reg>
                    </head>
                    <notatedMusic>
```
