### ISSUE TITLE
manglende tekst

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/middelaldertekster#83]
Tekst vises ikke under div2 og div3: https://melodier.dsl.dk/document.xq?doc=Th_1569_LN1426_302v.xml

**Comment by axgeertinger** [comment]
Det skyldes så vidt jeg kan se, at antifon + nunc dimittis er kodet i selvstændige div'er i TEI, altså div'er på samme niveau som den div med type="psalm", som første del ligger i. Enten skal det ændres i TEI, så det hele kommer til at ligge i samme div, eller også skal jeg ændre det script, som henter teksten ind i melodibasevisningen. Det sidste er lidt problematisk, fordi det vil give problemer med forkert tekst andre steder, så vidt jeg kan se af et par stikprøver. Jeg kan ikke lige overskue konsekvenserne. Det første vil derimod ændre i kapitelinddelingen i Thomissøn, fordi kapitel 19.16-19.18 så vil blive slået sammen til et, men det gør formentlig ikke noget.

**Comment by axgeertinger** [comment]
fixed
