### ISSUE TITLE
kan ikke hente tekst

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/middelaldertekster#84]
Poster i Mortensen 1529 kan ikke hente teksten, som skal vises under noderne. 
Se: 
https://melodier.dsl.dk/document.xq?doc=Mo_1528/Mo_1528_LN0174_000a02v.xml 

og 
https://melodier.dsl.dk/document.xq?doc=Mo_1528/Mo_1528_LN0174_000B03r.xml

**Comment by axgeertinger** [comment]
Løst ved at omdøbe alle forekomster af Mo_1528 til Mo_1529 og claus-mortensen-messe-1528 til claus-mortensen-messe-1529
